# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_ui_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #F5FAFF")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_setting = QtWidgets.QPushButton(self.centralwidget)
        self.button_setting.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_setting.setFont(font)
        self.button_setting.setStyleSheet("border: 3px solid #81D4FA;\n"
"border-radius: 10px;\n"
"background-color: #f8f9fa;\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}")
        self.button_setting.setObjectName("button_setting")
        self.general_status = QtWidgets.QFrame(self.centralwidget)
        self.general_status.setGeometry(QtCore.QRect(10, 50, 1001, 231))
        self.general_status.setStyleSheet("border: 3px solid #81D4FA;\n"
"border-radius: 10px;\n"
"background-color: #f8f9fa;\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}")
        self.general_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.general_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.general_status.setObjectName("general_status")
        self.general_status_icon = QtWidgets.QLabel(self.general_status)
        self.general_status_icon.setGeometry(QtCore.QRect(210, 20, 191, 191))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.general_status_icon.setFont(font)
        self.general_status_icon.setStyleSheet("border: 3px solid #81D4FA;\n"
"border-radius: 16px;\n"
"background-color: #F0F8FF;\n"
"padding: 12px;")
        self.general_status_icon.setObjectName("general_status_icon")
        self.label_39 = QtWidgets.QLabel(self.general_status)
        self.label_39.setGeometry(QtCore.QRect(640, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(False)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("border: none;\n"
"    border-radius: 0px;  color: #2742F5")
        self.label_39.setObjectName("label_39")
        self.status_value = QtWidgets.QLabel(self.general_status)
        self.status_value.setGeometry(QtCore.QRect(780, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.status_value.setFont(font)
        self.status_value.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #455A64")
        self.status_value.setObjectName("status_value")
        self.label_38 = QtWidgets.QLabel(self.general_status)
        self.label_38.setGeometry(QtCore.QRect(640, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #2196F3")
        self.label_38.setObjectName("label_38")
        self.server_connect = QtWidgets.QLabel(self.general_status)
        self.server_connect.setGeometry(QtCore.QRect(780, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.server_connect.setFont(font)
        self.server_connect.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #4CAF50\n"
"")
        self.server_connect.setObjectName("server_connect")
        self.label_37 = QtWidgets.QLabel(self.general_status)
        self.label_37.setGeometry(QtCore.QRect(640, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #455A64\n"
"")
        self.label_37.setObjectName("label_37")
        self.label_49 = QtWidgets.QLabel(self.general_status)
        self.label_49.setGeometry(QtCore.QRect(640, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #4CAF50\n"
"")
        self.label_49.setObjectName("label_49")
        self.no_pin_value = QtWidgets.QLabel(self.general_status)
        self.no_pin_value.setGeometry(QtCore.QRect(780, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.no_pin_value.setFont(font)
        self.no_pin_value.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #2742F5\n"
"\n"
"")
        self.no_pin_value.setObjectName("no_pin_value")
        self.mode_value = QtWidgets.QLabel(self.general_status)
        self.mode_value.setGeometry(QtCore.QRect(780, 140, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.mode_value.setFont(font)
        self.mode_value.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #2196F3\n"
"")
        self.mode_value.setObjectName("mode_value")
        self.label_40 = QtWidgets.QLabel(self.general_status)
        self.label_40.setGeometry(QtCore.QRect(640, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #2196F3")
        self.label_40.setObjectName("label_40")
        self.wifi_value = QtWidgets.QLabel(self.general_status)
        self.wifi_value.setGeometry(QtCore.QRect(780, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.wifi_value.setFont(font)
        self.wifi_value.setStyleSheet("border: none;\n"
"    border-radius: 0px; color: #2196F3")
        self.wifi_value.setObjectName("wifi_value")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(860, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: #278EF5")
        self.label_26.setObjectName("label_26")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 300, 1001, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_pin_1 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_pin_1.setStyleSheet("border: 3px solid #81D4FA;\n"
"border-radius: 10px;\n"
"background-color: #f8f9fa;\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}")
        self.frame_pin_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pin_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pin_1.setObjectName("frame_pin_1")
        self.label_202 = QtWidgets.QLabel(self.frame_pin_1)
        self.label_202.setGeometry(QtCore.QRect(70, 10, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_202.setFont(font)
        self.label_202.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_202.setObjectName("label_202")
        self.label_203 = QtWidgets.QLabel(self.frame_pin_1)
        self.label_203.setGeometry(QtCore.QRect(70, 70, 51, 17))
        self.label_203.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_203.setObjectName("label_203")
        self.progressBar_pin_1_n = QtWidgets.QProgressBar(self.frame_pin_1)
        self.progressBar_pin_1_n.setGeometry(QtCore.QRect(21, 100, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_pin_1_n.setFont(font)
        self.progressBar_pin_1_n.setStyleSheet("QProgressBar {\n"
"    border: 3px solid #81D4FA;\n"
"    border-radius: 18px;              /* tăng radius lên để chunk có không gian tròn */\n"
"    background-color: #E0F7FA;\n"
"    text-align: center;\n"
"    color: transparent;               /* ẩn text % mặc định nếu bạn dùng label riêng */\n"
"    height: 38px;                     /* tăng height nhẹ để chunk không bị ép */\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4FC3F7;\n"
"    border-radius: 15px;              /* radius của chunk nhỏ hơn groove 2-3px để vừa khít */\n"
"    margin: 3px;                      /* margin nhỏ để chunk không dính sát viền groove */\n"
"    border: none;\n"
"}")
        self.progressBar_pin_1_n.setProperty("value", 24)
        self.progressBar_pin_1_n.setTextVisible(False)
        self.progressBar_pin_1_n.setObjectName("progressBar_pin_1_n")
        self.label_204 = QtWidgets.QLabel(self.frame_pin_1)
        self.label_204.setGeometry(QtCore.QRect(20, 160, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_204.setFont(font)
        self.label_204.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_204.setObjectName("label_204")
        self.label_205 = QtWidgets.QLabel(self.frame_pin_1)
        self.label_205.setGeometry(QtCore.QRect(20, 180, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_205.setFont(font)
        self.label_205.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_205.setObjectName("label_205")
        self.label_206 = QtWidgets.QLabel(self.frame_pin_1)
        self.label_206.setGeometry(QtCore.QRect(20, 200, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_206.setFont(font)
        self.label_206.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_206.setObjectName("label_206")
        self.pin_1_vol_value_n = QtWidgets.QLabel(self.frame_pin_1)
        self.pin_1_vol_value_n.setGeometry(QtCore.QRect(100, 160, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_1_vol_value_n.setFont(font)
        self.pin_1_vol_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_1_vol_value_n.setObjectName("pin_1_vol_value_n")
        self.pin_1_temp_value_n = QtWidgets.QLabel(self.frame_pin_1)
        self.pin_1_temp_value_n.setGeometry(QtCore.QRect(100, 180, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_1_temp_value_n.setFont(font)
        self.pin_1_temp_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_1_temp_value_n.setObjectName("pin_1_temp_value_n")
        self.pin_1_status_value_n = QtWidgets.QLabel(self.frame_pin_1)
        self.pin_1_status_value_n.setGeometry(QtCore.QRect(100, 200, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pin_1_status_value_n.setFont(font)
        self.pin_1_status_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_1_status_value_n.setObjectName("pin_1_status_value_n")
        self.label_207 = QtWidgets.QLabel(self.frame_pin_1)
        self.label_207.setGeometry(QtCore.QRect(130, 160, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_207.setFont(font)
        self.label_207.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_207.setObjectName("label_207")
        self.label_208 = QtWidgets.QLabel(self.frame_pin_1)
        self.label_208.setGeometry(QtCore.QRect(130, 180, 21, 17))
        self.label_208.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_208.setObjectName("label_208")
        self.horizontalLayout_4.addWidget(self.frame_pin_1)
        self.frame_pin_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_pin_2.setStyleSheet("border: 3px solid #81D4FA;\n"
"border-radius: 10px;\n"
"background-color: #f8f9fa;\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}")
        self.frame_pin_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pin_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pin_2.setObjectName("frame_pin_2")
        self.label_195 = QtWidgets.QLabel(self.frame_pin_2)
        self.label_195.setGeometry(QtCore.QRect(70, 10, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_195.setFont(font)
        self.label_195.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_195.setObjectName("label_195")
        self.label_196 = QtWidgets.QLabel(self.frame_pin_2)
        self.label_196.setGeometry(QtCore.QRect(70, 70, 51, 17))
        self.label_196.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_196.setObjectName("label_196")
        self.progressBar_pin_2_n = QtWidgets.QProgressBar(self.frame_pin_2)
        self.progressBar_pin_2_n.setGeometry(QtCore.QRect(20, 100, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_pin_2_n.setFont(font)
        self.progressBar_pin_2_n.setStyleSheet("QProgressBar {\n"
"    border: 3px solid #81D4FA;\n"
"    border-radius: 18px;              /* tăng radius lên để chunk có không gian tròn */\n"
"    background-color: #E0F7FA;\n"
"    text-align: center;\n"
"    color: transparent;               /* ẩn text % mặc định nếu bạn dùng label riêng */\n"
"    height: 38px;                     /* tăng height nhẹ để chunk không bị ép */\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4FC3F7;\n"
"    border-radius: 15px;              /* radius của chunk nhỏ hơn groove 2-3px để vừa khít */\n"
"    margin: 3px;                      /* margin nhỏ để chunk không dính sát viền groove */\n"
"    border: none;\n"
"}")
        self.progressBar_pin_2_n.setProperty("value", 24)
        self.progressBar_pin_2_n.setTextVisible(False)
        self.progressBar_pin_2_n.setObjectName("progressBar_pin_2_n")
        self.label_197 = QtWidgets.QLabel(self.frame_pin_2)
        self.label_197.setGeometry(QtCore.QRect(20, 160, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_197.setFont(font)
        self.label_197.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_197.setObjectName("label_197")
        self.label_198 = QtWidgets.QLabel(self.frame_pin_2)
        self.label_198.setGeometry(QtCore.QRect(20, 180, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_198.setFont(font)
        self.label_198.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_198.setObjectName("label_198")
        self.label_199 = QtWidgets.QLabel(self.frame_pin_2)
        self.label_199.setGeometry(QtCore.QRect(20, 200, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_199.setFont(font)
        self.label_199.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_199.setObjectName("label_199")
        self.pin_2_vol_value_n = QtWidgets.QLabel(self.frame_pin_2)
        self.pin_2_vol_value_n.setGeometry(QtCore.QRect(100, 160, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_2_vol_value_n.setFont(font)
        self.pin_2_vol_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_2_vol_value_n.setObjectName("pin_2_vol_value_n")
        self.pin_2_temp_value_n = QtWidgets.QLabel(self.frame_pin_2)
        self.pin_2_temp_value_n.setGeometry(QtCore.QRect(100, 180, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_2_temp_value_n.setFont(font)
        self.pin_2_temp_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_2_temp_value_n.setObjectName("pin_2_temp_value_n")
        self.pin_2_status_value_n = QtWidgets.QLabel(self.frame_pin_2)
        self.pin_2_status_value_n.setGeometry(QtCore.QRect(100, 200, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pin_2_status_value_n.setFont(font)
        self.pin_2_status_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_2_status_value_n.setObjectName("pin_2_status_value_n")
        self.label_200 = QtWidgets.QLabel(self.frame_pin_2)
        self.label_200.setGeometry(QtCore.QRect(130, 160, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_200.setFont(font)
        self.label_200.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_200.setObjectName("label_200")
        self.label_201 = QtWidgets.QLabel(self.frame_pin_2)
        self.label_201.setGeometry(QtCore.QRect(130, 180, 21, 17))
        self.label_201.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_201.setObjectName("label_201")
        self.horizontalLayout_4.addWidget(self.frame_pin_2)
        self.frame_pin_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_pin_3.setFont(font)
        self.frame_pin_3.setStyleSheet("border: 3px solid #81D4FA;\n"
"border-radius: 10px;\n"
"background-color: #f8f9fa;\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}")
        self.frame_pin_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pin_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pin_3.setObjectName("frame_pin_3")
        self.label_181 = QtWidgets.QLabel(self.frame_pin_3)
        self.label_181.setGeometry(QtCore.QRect(70, 10, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_181.setFont(font)
        self.label_181.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_181.setObjectName("label_181")
        self.label_182 = QtWidgets.QLabel(self.frame_pin_3)
        self.label_182.setGeometry(QtCore.QRect(70, 70, 51, 17))
        self.label_182.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_182.setObjectName("label_182")
        self.progressBar_pin_3_n = QtWidgets.QProgressBar(self.frame_pin_3)
        self.progressBar_pin_3_n.setGeometry(QtCore.QRect(20, 100, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_pin_3_n.setFont(font)
        self.progressBar_pin_3_n.setStyleSheet("QProgressBar {\n"
"    border: 3px solid #81D4FA;\n"
"    border-radius: 18px;              /* tăng radius lên để chunk có không gian tròn */\n"
"    background-color: #E0F7FA;\n"
"    text-align: center;\n"
"    color: transparent;               /* ẩn text % mặc định nếu bạn dùng label riêng */\n"
"    height: 38px;                     /* tăng height nhẹ để chunk không bị ép */\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4FC3F7;\n"
"    border-radius: 15px;              /* radius của chunk nhỏ hơn groove 2-3px để vừa khít */\n"
"    margin: 3px;                      /* margin nhỏ để chunk không dính sát viền groove */\n"
"    border: none;\n"
"}")
        self.progressBar_pin_3_n.setProperty("value", 24)
        self.progressBar_pin_3_n.setTextVisible(False)
        self.progressBar_pin_3_n.setObjectName("progressBar_pin_3_n")
        self.label_183 = QtWidgets.QLabel(self.frame_pin_3)
        self.label_183.setGeometry(QtCore.QRect(20, 160, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_183.setFont(font)
        self.label_183.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_183.setObjectName("label_183")
        self.label_184 = QtWidgets.QLabel(self.frame_pin_3)
        self.label_184.setGeometry(QtCore.QRect(20, 180, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_184.setFont(font)
        self.label_184.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_184.setObjectName("label_184")
        self.label_185 = QtWidgets.QLabel(self.frame_pin_3)
        self.label_185.setGeometry(QtCore.QRect(20, 200, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_185.setFont(font)
        self.label_185.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_185.setObjectName("label_185")
        self.pin_3_vol_value_n = QtWidgets.QLabel(self.frame_pin_3)
        self.pin_3_vol_value_n.setGeometry(QtCore.QRect(100, 160, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_3_vol_value_n.setFont(font)
        self.pin_3_vol_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_3_vol_value_n.setObjectName("pin_3_vol_value_n")
        self.pin_3_temp_value_n = QtWidgets.QLabel(self.frame_pin_3)
        self.pin_3_temp_value_n.setGeometry(QtCore.QRect(100, 180, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_3_temp_value_n.setFont(font)
        self.pin_3_temp_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_3_temp_value_n.setObjectName("pin_3_temp_value_n")
        self.pin_3_status_value_n = QtWidgets.QLabel(self.frame_pin_3)
        self.pin_3_status_value_n.setGeometry(QtCore.QRect(100, 200, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pin_3_status_value_n.setFont(font)
        self.pin_3_status_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_3_status_value_n.setObjectName("pin_3_status_value_n")
        self.label_186 = QtWidgets.QLabel(self.frame_pin_3)
        self.label_186.setGeometry(QtCore.QRect(130, 160, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_186.setFont(font)
        self.label_186.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_186.setObjectName("label_186")
        self.label_187 = QtWidgets.QLabel(self.frame_pin_3)
        self.label_187.setGeometry(QtCore.QRect(130, 180, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_187.setFont(font)
        self.label_187.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_187.setObjectName("label_187")
        self.horizontalLayout_4.addWidget(self.frame_pin_3)
        self.frame_pin_4 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_pin_4.setStyleSheet("border: 3px solid #81D4FA;\n"
"border-radius: 10px;\n"
"background-color: #f8f9fa;\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}")
        self.frame_pin_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pin_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pin_4.setObjectName("frame_pin_4")
        self.label_188 = QtWidgets.QLabel(self.frame_pin_4)
        self.label_188.setGeometry(QtCore.QRect(70, 10, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_188.setFont(font)
        self.label_188.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_188.setObjectName("label_188")
        self.label_189 = QtWidgets.QLabel(self.frame_pin_4)
        self.label_189.setGeometry(QtCore.QRect(70, 70, 51, 17))
        self.label_189.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_189.setObjectName("label_189")
        self.progressBar_pin_4_n = QtWidgets.QProgressBar(self.frame_pin_4)
        self.progressBar_pin_4_n.setGeometry(QtCore.QRect(20, 100, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_pin_4_n.setFont(font)
        self.progressBar_pin_4_n.setStyleSheet("QProgressBar {\n"
"    border: 3px solid #81D4FA;\n"
"    border-radius: 18px;              /* tăng radius lên để chunk có không gian tròn */\n"
"    background-color: #E0F7FA;\n"
"    text-align: center;\n"
"    color: transparent;               /* ẩn text % mặc định nếu bạn dùng label riêng */\n"
"    height: 38px;                     /* tăng height nhẹ để chunk không bị ép */\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4FC3F7;\n"
"    border-radius: 15px;              /* radius của chunk nhỏ hơn groove 2-3px để vừa khít */\n"
"    margin: 3px;                      /* margin nhỏ để chunk không dính sát viền groove */\n"
"    border: none;\n"
"}")
        self.progressBar_pin_4_n.setProperty("value", 24)
        self.progressBar_pin_4_n.setTextVisible(False)
        self.progressBar_pin_4_n.setObjectName("progressBar_pin_4_n")
        self.label_190 = QtWidgets.QLabel(self.frame_pin_4)
        self.label_190.setGeometry(QtCore.QRect(20, 160, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_190.setFont(font)
        self.label_190.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_190.setObjectName("label_190")
        self.label_191 = QtWidgets.QLabel(self.frame_pin_4)
        self.label_191.setGeometry(QtCore.QRect(20, 180, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_191.setFont(font)
        self.label_191.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_191.setObjectName("label_191")
        self.label_192 = QtWidgets.QLabel(self.frame_pin_4)
        self.label_192.setGeometry(QtCore.QRect(20, 200, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_192.setFont(font)
        self.label_192.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_192.setObjectName("label_192")
        self.pin_4_vol_value_n = QtWidgets.QLabel(self.frame_pin_4)
        self.pin_4_vol_value_n.setGeometry(QtCore.QRect(100, 160, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_4_vol_value_n.setFont(font)
        self.pin_4_vol_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_4_vol_value_n.setObjectName("pin_4_vol_value_n")
        self.pin_4_temp_value_n = QtWidgets.QLabel(self.frame_pin_4)
        self.pin_4_temp_value_n.setGeometry(QtCore.QRect(100, 180, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_4_temp_value_n.setFont(font)
        self.pin_4_temp_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_4_temp_value_n.setObjectName("pin_4_temp_value_n")
        self.pin_4_status_value_n = QtWidgets.QLabel(self.frame_pin_4)
        self.pin_4_status_value_n.setGeometry(QtCore.QRect(100, 200, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pin_4_status_value_n.setFont(font)
        self.pin_4_status_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_4_status_value_n.setObjectName("pin_4_status_value_n")
        self.label_193 = QtWidgets.QLabel(self.frame_pin_4)
        self.label_193.setGeometry(QtCore.QRect(130, 160, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_193.setFont(font)
        self.label_193.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_193.setObjectName("label_193")
        self.label_194 = QtWidgets.QLabel(self.frame_pin_4)
        self.label_194.setGeometry(QtCore.QRect(130, 180, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_194.setFont(font)
        self.label_194.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_194.setObjectName("label_194")
        self.horizontalLayout_4.addWidget(self.frame_pin_4)
        self.frame_pin_5 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_pin_5.setStyleSheet("border: 3px solid #81D4FA;\n"
"border-radius: 10px;\n"
"background-color: #f8f9fa;\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}")
        self.frame_pin_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pin_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pin_5.setObjectName("frame_pin_5")
        self.label_209 = QtWidgets.QLabel(self.frame_pin_5)
        self.label_209.setGeometry(QtCore.QRect(70, 10, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_209.setFont(font)
        self.label_209.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_209.setObjectName("label_209")
        self.label_210 = QtWidgets.QLabel(self.frame_pin_5)
        self.label_210.setGeometry(QtCore.QRect(70, 70, 51, 17))
        self.label_210.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_210.setObjectName("label_210")
        self.progressBar_pin_5_n = QtWidgets.QProgressBar(self.frame_pin_5)
        self.progressBar_pin_5_n.setGeometry(QtCore.QRect(20, 100, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_pin_5_n.setFont(font)
        self.progressBar_pin_5_n.setStyleSheet("QProgressBar {\n"
"    border: 3px solid #81D4FA;\n"
"    border-radius: 18px;              /* tăng radius lên để chunk có không gian tròn */\n"
"    background-color: #E0F7FA;\n"
"    text-align: center;\n"
"    color: transparent;               /* ẩn text % mặc định nếu bạn dùng label riêng */\n"
"    height: 38px;                     /* tăng height nhẹ để chunk không bị ép */\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4FC3F7;\n"
"    border-radius: 15px;              /* radius của chunk nhỏ hơn groove 2-3px để vừa khít */\n"
"    margin: 3px;                      /* margin nhỏ để chunk không dính sát viền groove */\n"
"    border: none;\n"
"}")
        self.progressBar_pin_5_n.setProperty("value", 24)
        self.progressBar_pin_5_n.setTextVisible(False)
        self.progressBar_pin_5_n.setObjectName("progressBar_pin_5_n")
        self.label_211 = QtWidgets.QLabel(self.frame_pin_5)
        self.label_211.setGeometry(QtCore.QRect(20, 160, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_211.setFont(font)
        self.label_211.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_211.setObjectName("label_211")
        self.label_212 = QtWidgets.QLabel(self.frame_pin_5)
        self.label_212.setGeometry(QtCore.QRect(20, 180, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_212.setFont(font)
        self.label_212.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_212.setObjectName("label_212")
        self.label_213 = QtWidgets.QLabel(self.frame_pin_5)
        self.label_213.setGeometry(QtCore.QRect(20, 200, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_213.setFont(font)
        self.label_213.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_213.setObjectName("label_213")
        self.pin_5_vol_value_n = QtWidgets.QLabel(self.frame_pin_5)
        self.pin_5_vol_value_n.setGeometry(QtCore.QRect(100, 160, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_5_vol_value_n.setFont(font)
        self.pin_5_vol_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_5_vol_value_n.setObjectName("pin_5_vol_value_n")
        self.pin_5_temp_value_n = QtWidgets.QLabel(self.frame_pin_5)
        self.pin_5_temp_value_n.setGeometry(QtCore.QRect(100, 180, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pin_5_temp_value_n.setFont(font)
        self.pin_5_temp_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_5_temp_value_n.setObjectName("pin_5_temp_value_n")
        self.pin_5_status_value_n = QtWidgets.QLabel(self.frame_pin_5)
        self.pin_5_status_value_n.setGeometry(QtCore.QRect(100, 200, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pin_5_status_value_n.setFont(font)
        self.pin_5_status_value_n.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.pin_5_status_value_n.setObjectName("pin_5_status_value_n")
        self.label_214 = QtWidgets.QLabel(self.frame_pin_5)
        self.label_214.setGeometry(QtCore.QRect(130, 160, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_214.setFont(font)
        self.label_214.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_214.setObjectName("label_214")
        self.label_215 = QtWidgets.QLabel(self.frame_pin_5)
        self.label_215.setGeometry(QtCore.QRect(130, 180, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_215.setFont(font)
        self.label_215.setStyleSheet("border: none;\n"
"    border-radius: 0px;")
        self.label_215.setObjectName("label_215")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_pin_5)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 140, 81, 31))
        self.pushButton_5.setStyleSheet("background-color: #FF9800;\n"
"color: white;\n"
"font-size: 12px;\n"
"border-radius: 50%;\n"
"width: 60px;\n"
"height: 60px;\n"
"text-align: center;\n"
"padding: 10px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.frame_pin_5)
        self.replace_button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.replace_button_1.setGeometry(QtCore.QRect(70, 540, 81, 31))
        self.replace_button_1.setStyleSheet("background-color: #FF9800;\n"
"color: white;\n"
"font-size: 12px;\n"
"border-radius: 50%;\n"
"width: 60px;\n"
"height: 60px;\n"
"text-align: center;\n"
"padding: 10px;")
        self.replace_button_1.setObjectName("replace_button_1")
        self.replace_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.replace_button_2.setGeometry(QtCore.QRect(270, 540, 81, 31))
        self.replace_button_2.setStyleSheet("background-color: #FF9800;\n"
"color: white;\n"
"font-size: 12px;\n"
"border-radius: 50%;\n"
"width: 60px;\n"
"height: 60px;\n"
"text-align: center;\n"
"padding: 10px;")
        self.replace_button_2.setObjectName("replace_button_2")
        self.replace_button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.replace_button_3.setGeometry(QtCore.QRect(470, 540, 81, 31))
        self.replace_button_3.setStyleSheet("background-color: #FF9800;\n"
"color: white;\n"
"font-size: 12px;\n"
"border-radius: 50%;\n"
"width: 60px;\n"
"height: 60px;\n"
"text-align: center;\n"
"padding: 10px;")
        self.replace_button_3.setObjectName("replace_button_3")
        self.replace_button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.replace_button_4.setGeometry(QtCore.QRect(670, 540, 81, 31))
        self.replace_button_4.setStyleSheet("background-color: #FF9800;\n"
"color: white;\n"
"font-size: 12px;\n"
"border-radius: 50%;\n"
"width: 60px;\n"
"height: 60px;\n"
"text-align: center;\n"
"padding: 10px;")
        self.replace_button_4.setObjectName("replace_button_4")
        self.replace_button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.replace_button_5.setGeometry(QtCore.QRect(870, 540, 81, 31))
        self.replace_button_5.setStyleSheet("background-color: #FF9800;\n"
"color: white;\n"
"font-size: 12px;\n"
"border-radius: 50%;\n"
"width: 60px;\n"
"height: 60px;\n"
"text-align: center;\n"
"padding: 10px;")
        self.replace_button_5.setObjectName("replace_button_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_setting.setText(_translate("MainWindow", "⚙"))
        self.general_status_icon.setText(_translate("MainWindow", "🤖💤"))
        self.label_39.setText(_translate("MainWindow", "Số lượng pin:"))
        self.status_value.setText(_translate("MainWindow", "BUSY"))
        self.label_38.setText(_translate("MainWindow", "Mode:"))
        self.server_connect.setText(_translate("MainWindow", "OK"))
        self.label_37.setText(_translate("MainWindow", "Trạng thái:"))
        self.label_49.setText(_translate("MainWindow", "Kết nối server:"))
        self.no_pin_value.setText(_translate("MainWindow", "5"))
        self.mode_value.setText(_translate("MainWindow", "Auto"))
        self.label_40.setText(_translate("MainWindow", "Kết Nối Wi-fi:"))
        self.wifi_value.setText(_translate("MainWindow", "OK"))
        self.label_26.setText(_translate("MainWindow", "VINMOTION"))
        self.label_202.setText(_translate("MainWindow", "🔋"))
        self.label_203.setText(_translate("MainWindow", "  PIN 1"))
        self.label_204.setText(_translate("MainWindow", "Điện áp:"))
        self.label_205.setText(_translate("MainWindow", "Nhiệt độ:"))
        self.label_206.setText(_translate("MainWindow", "Trạng thái:"))
        self.pin_1_vol_value_n.setText(_translate("MainWindow", "10"))
        self.pin_1_temp_value_n.setText(_translate("MainWindow", "20"))
        self.pin_1_status_value_n.setText(_translate("MainWindow", "OK"))
        self.label_207.setText(_translate("MainWindow", "V"))
        self.label_208.setText(_translate("MainWindow", "*C"))
        self.label_195.setText(_translate("MainWindow", "🔋"))
        self.label_196.setText(_translate("MainWindow", "  PIN 2"))
        self.label_197.setText(_translate("MainWindow", "Điện áp:"))
        self.label_198.setText(_translate("MainWindow", "Nhiệt độ:"))
        self.label_199.setText(_translate("MainWindow", "Trạng thái:"))
        self.pin_2_vol_value_n.setText(_translate("MainWindow", "10"))
        self.pin_2_temp_value_n.setText(_translate("MainWindow", "20"))
        self.pin_2_status_value_n.setText(_translate("MainWindow", "OK"))
        self.label_200.setText(_translate("MainWindow", "V"))
        self.label_201.setText(_translate("MainWindow", "*C"))
        self.label_181.setText(_translate("MainWindow", "🔋"))
        self.label_182.setText(_translate("MainWindow", "  PIN 3"))
        self.label_183.setText(_translate("MainWindow", "Điện áp:"))
        self.label_184.setText(_translate("MainWindow", "Nhiệt độ:"))
        self.label_185.setText(_translate("MainWindow", "Trạng thái:"))
        self.pin_3_vol_value_n.setText(_translate("MainWindow", "10"))
        self.pin_3_temp_value_n.setText(_translate("MainWindow", "20"))
        self.pin_3_status_value_n.setText(_translate("MainWindow", "OK"))
        self.label_186.setText(_translate("MainWindow", "V"))
        self.label_187.setText(_translate("MainWindow", "*C"))
        self.label_188.setText(_translate("MainWindow", "🔋"))
        self.label_189.setText(_translate("MainWindow", "  PIN 4"))
        self.label_190.setText(_translate("MainWindow", "Điện áp:"))
        self.label_191.setText(_translate("MainWindow", "Nhiệt độ:"))
        self.label_192.setText(_translate("MainWindow", "Trạng thái:"))
        self.pin_4_vol_value_n.setText(_translate("MainWindow", "10"))
        self.pin_4_temp_value_n.setText(_translate("MainWindow", "20"))
        self.pin_4_status_value_n.setText(_translate("MainWindow", "OK"))
        self.label_193.setText(_translate("MainWindow", "V"))
        self.label_194.setText(_translate("MainWindow", "*C"))
        self.label_209.setText(_translate("MainWindow", "🔋"))
        self.label_210.setText(_translate("MainWindow", "  PIN 5"))
        self.label_211.setText(_translate("MainWindow", "Điện áp:"))
        self.label_212.setText(_translate("MainWindow", "Nhiệt độ:"))
        self.label_213.setText(_translate("MainWindow", "Trạng thái:"))
        self.pin_5_vol_value_n.setText(_translate("MainWindow", "10"))
        self.pin_5_temp_value_n.setText(_translate("MainWindow", "20"))
        self.pin_5_status_value_n.setText(_translate("MainWindow", "OK"))
        self.label_214.setText(_translate("MainWindow", "V"))
        self.label_215.setText(_translate("MainWindow", "*C"))
        self.pushButton_5.setText(_translate("MainWindow", "↩  Rút pin"))
        self.replace_button_1.setText(_translate("MainWindow", "↩  Rút pin"))
        self.replace_button_2.setText(_translate("MainWindow", "↩  Rút pin"))
        self.replace_button_3.setText(_translate("MainWindow", "↩  Rút pin"))
        self.replace_button_4.setText(_translate("MainWindow", "↩  Rút pin"))
        self.replace_button_5.setText(_translate("MainWindow", "↩  Rút pin"))
