# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pin_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_pin(object):
    def setupUi(self, Dialog_pin):
        Dialog_pin.setObjectName("Dialog_pin")
        Dialog_pin.resize(349, 506)
        Dialog_pin.setStyleSheet("    QPushButton {\n"
"        background-color: #0288D1;\n"
"        color: white;\n"
"        border-radius: 10px;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        padding: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #0277BD;\n"
"    }")
        self.frame = QtWidgets.QFrame(Dialog_pin)
        self.frame.setGeometry(QtCore.QRect(20, 10, 311, 41))
        self.frame.setStyleSheet("border: none;\n"
"border-radius: 20px;          /* bo góc 12px – chỉnh lớn hơn nếu muốn tròn hơn */\n"
"background-color: #E0F7FA;    /* xanh nước biển nhạt đẹp nhất */\n"
"padding: 10px;                /* khoảng cách bên trong để nội dung không sát góc */")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(37, 1, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #01579B")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Dialog_pin)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 311, 401))
        self.tableWidget.setStyleSheet("            QTableWidget {\n"
"                gridline-color: #81D4FA;\n"
"                font-size: 16px;\n"
"                alternate-background-color: #F0F8FF;\n"
"            }\n"
"            QHeaderView::section {\n"
"                background-color: #0288D1;\n"
"                color: white;\n"
"                padding: 8px;\n"
"                font-weight: bold;\n"
"                border: 1px solid #81D4FA;\n"
"            }\n"
"            QTableWidget::item {\n"
"                padding: 6px;\n"
"            }")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(80)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.close_button_pin_dialog_1 = QtWidgets.QPushButton(Dialog_pin)
        self.close_button_pin_dialog_1.setGeometry(QtCore.QRect(20, 470, 311, 31))
        self.close_button_pin_dialog_1.setStyleSheet("    QPushButton {\n"
"        background-color: #0288D1;\n"
"        color: white;\n"
"        border-radius: 10px;\n"
"        font-size: 10px;\n"
"        font-weight: bold;\n"
"        padding: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #0277BD;\n"
"    }")
        self.close_button_pin_dialog_1.setObjectName("close_button_pin_dialog_1")

        self.retranslateUi(Dialog_pin)
        QtCore.QMetaObject.connectSlotsByName(Dialog_pin)

    def retranslateUi(self, Dialog_pin):
        _translate = QtCore.QCoreApplication.translate
        Dialog_pin.setWindowTitle(_translate("Dialog_pin", "Dialog"))
        self.label.setText(_translate("Dialog_pin", "       Thông số chi tiết"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_pin", "Thông số"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_pin", "Giá trị"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog_pin", "SOC"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog_pin", "0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Dialog_pin", "SOH"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Dialog_pin", "0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Dialog_pin", "Current (mA)"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Dialog_pin", "0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Dialog_pin", "Pack Voltage (V)"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Dialog_pin", "0"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Dialog_pin", "Stack Voltage"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Dialog_pin", "0"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Dialog_pin", "Faults"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Dialog_pin", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.close_button_pin_dialog_1.setText(_translate("Dialog_pin", "Đóng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_pin = QtWidgets.QDialog()
    ui = Ui_Dialog_pin()
    ui.setupUi(Dialog_pin)
    Dialog_pin.show()
    sys.exit(app.exec_())
