# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_setting(object):
    def setupUi(self, Dialog_setting):
        Dialog_setting.setObjectName("Dialog_setting")
        Dialog_setting.resize(336, 246)
        Dialog_setting.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #81D4FA;      /* viền xanh nhạt */\n"
"    border-radius: 12px;            /* bo góc đẹp */\n"
"    background-color: white;        /* nền trắng */\n"
"    margin-top: 20px;               /* khoảng cách tiêu đề */\n"
"    padding-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"    color: #01579B;                 /* chữ tiêu đề xanh đậm */\n"
"    font-weight: bold;\n"
"    background-color: #E0F7FA;      /* nền tiêu đề xanh nhạt */\n"
"    border: 1px solid #81D4FA;\n"
"    border-radius: 6px;\n"
"}")
        self.toolBox = QtWidgets.QToolBox(Dialog_setting)
        self.toolBox.setGeometry(QtCore.QRect(60, 50, 231, 130))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 231, 66))
        self.page.setObjectName("page")
        self.checkBox = QtWidgets.QCheckBox(self.page)
        self.checkBox.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 30, 92, 23))
        self.checkBox_2.setObjectName("checkBox_2")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 231, 66))
        self.page_2.setObjectName("page_2")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 161, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 30, 161, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolBox.addItem(self.page_2, "")
        self.frame = QtWidgets.QFrame(Dialog_setting)
        self.frame.setGeometry(QtCore.QRect(60, 10, 201, 41))
        self.frame.setStyleSheet("border: none;\n"
"border-radius: 20px;          /* bo góc 12px – chỉnh lớn hơn nếu muốn tròn hơn */\n"
"background-color: #E0F7FA;    /* xanh nước biển nhạt đẹp nhất */\n"
"padding: 11px;                /* khoảng cách bên trong để nội dung không sát góc */")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #01579B")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog_setting)
        self.pushButton.setGeometry(QtCore.QRect(100, 200, 131, 25))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog_setting)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog_setting)

    def retranslateUi(self, Dialog_setting):
        _translate = QtCore.QCoreApplication.translate
        Dialog_setting.setWindowTitle(_translate("Dialog_setting", "Dialog"))
        self.checkBox.setText(_translate("Dialog_setting", "Auto"))
        self.checkBox_2.setText(_translate("Dialog_setting", "Manual"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog_setting", "Chế độ hoạt động"))
        self.lineEdit.setPlaceholderText(_translate("Dialog_setting", "Tên WI-fi"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog_setting", "Password"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Dialog_setting", "Kết nối wifi"))
        self.label.setText(_translate("Dialog_setting", "Cài đặt hệ thống"))
        self.pushButton.setText(_translate("Dialog_setting", "Lưu cài đăt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_setting = QtWidgets.QDialog()
    ui = Ui_Dialog_setting()
    ui.setupUi(Dialog_setting)
    Dialog_setting.show()
    sys.exit(app.exec_())
